name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y scons build-essential libsqlite3-dev libbz2-dev libreadline-dev libssl-dev libgdbm-dev libffi-dev liblzma-dev tk-dev texinfo autoconf libtool automake pkg-config

    - name: Install Buildozer and Dependencies
      run: |
        pip install --upgrade buildozer cython Kivy plyer

    - name: Configure buildozer.spec and Permissions
      run: |
        # Включаем лицензии SDK
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        # Выставляем Android API 34
        sed -i 's/android.api = 31/android.api = 34/g' buildozer.spec
        sed -i 's/android.api = 33/android.api = 34/g' buildozer.spec
        # ТРЕБУЕМЫЕ РАЗРЕШЕНИЯ: Добавляем права на Сеть и Wi-Fi в манифест Android приложения
        sed -i 's/android.permissions =/android.permissions = INTERNET,ACCESS_NETWORK_STATE,ACCESS_WIFI_STATE/g' buildozer.spec

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
